name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
    - name: Lint with flake8
      run: |
        poetry run task flake8
    - name: Run black
      run: |
        poetry run task black
    - name: Lint with isort
      run: |
        poetry run task isort
    - name: Test with Pytest
      run: |
        poetry run task download
        poetry run task test
